name: Voyager Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create env
        run: |
          echo "API_ID=36752111" > VoyagerBot.env
          echo "API_HASH=e0e2551f38b8ce83022699ae1e04a5ea" >> VoyagerBot.env
          echo "BOT_TOKEN=8697661935:AAEHPeWu6xfJUQdTpQaDG0NCFD6kDflVJwM" >> VoyagerBot.env
          echo "CHANNEL_ID=@VoyagersIPA" >> VoyagerBot.env
          echo "ADMIN_ID=115408334" >> VoyagerBot.env
      
      - name: Run bot
        run: timeout 21000 python bot.py || true
